# Generated by Django 5.1.5 on 2025-01-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_solicitudespacio_fecha_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudespacio',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Aprobado'), (3, 'Finalizada')], default=1),
        ),
    ]
