# Generated by Django 5.1.5 on 2025-01-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_alter_solicitudespacio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='role',
            field=models.CharField(choices=[('Coordinación', 'Coordinación'), ('Delegación Administrativa', 'Delegación Administrativa'), ('General', 'General')], default='General', max_length=50),
        ),
    ]
