# Generated by Django 5.1.5 on 2025-01-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_area_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='role',
        ),
        migrations.AlterField(
            model_name='solicitudespacio',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Aprobado'), (3, 'Rechazado')], default=1),
        ),
    ]
