# Generated by Django 5.1.5 on 2025-01-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_remove_area_role_alter_solicitudespacio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudespacio',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Aprobado'), (3, 'Finalizado')], default=1),
        ),
    ]
